### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by anjalit03** [anjalit03/Dazzle-and-Delight#2]
Update readme with proper defined details about how the website works to give new users a guide through.

**Comment by harith-hacky03** [comment]
I'm ready to work on it can you assign me?

**Comment by anjalit03** [comment]
Sure! Please go ahead with it!

**Comment by harith-hacky03** [comment]
@anjalit03  Can you please check it once and let me know if any changes is needed. Thank you

**Comment by anjalit03** [comment]
please do add one more line in contribution section that we already have a contribution file so people can go to the file and find more detailed information about how to contribute

**Comment by harith-hacky03** [comment]
@anjalit03  Please do check it now
