### ISSUE TITLE
Update README.md - Remove npm install Step Due to Missing package.json

### ISSUE THREAD

**Issue by Elisassa** [anjalit03/Dazzle-and-Delight#25]
I followed the steps in the README.md to run the project locally. When I reached the "Install Dependencies" step (npm install), I encountered an issue: there is no package.json file in the repository, which means npm install cannot be used.

**Comment by Elisassa** [comment]
pls assign me to fix this issue

**Comment by anjalit03** [comment]
Yes thankyou I have assigned it to you !

**Comment by Elisassa** [comment]
I have made PR pls help me check if it's ok
