### ISSUE TITLE
Login/sign up page ui improvements and code formatting

### ISSUE THREAD

**Issue by TonyStark-19** [anjalit03/Dazzle-and-Delight#29]
I will improve the login/sign-up pages with CSS improvements 
i will also increase the code formatting by deleting extra comments and spaces and by adding new spaces and comments where needed.
Your project is awe-inspiring.
Although i can work on your project as a whole,  for now, I will work on the login/sign-up page and code formatting only.
you can also tell me where you want improvements, I'm open to it

**Comment by TonyStark-19** [comment]
I will improve the design consistency which will make it look more good.

I will add hover effects , improve input boxes , overall layout , add margins , padding etc whatever needed

**Comment by anjalit03** [comment]
alright ! I'm assigning you!

**Comment by TonyStark-19** [comment]
Thanks!
I'll start the work tomorrow 
And please add hacktoberfest label also!
