### ISSUE TITLE
Website URL issue 

### ISSUE THREAD

**Issue by mahmoud-the-dev** [anjalit03/Dazzle-and-Delight#3]
the url in the about section of the repo is not valid
![image](https://github.com/user-attachments/assets/96ad17ba-1cf0-4117-a117-db194f4ae1fc)

**Comment by anjalit03** [comment]
yes for some reason the deployment on vercel is not working..... I am unable to understand the cause.... do you know how to fix this??

**Comment by mahmoud-the-dev** [comment]
I see you fixed it, 
but the CSS isn't read

**Comment by anjalit03** [comment]
Yes I was trying to fix it but now I'm stuck at this point why isn't it picking up css :(

**Comment by mahmoud-the-dev** [comment]
I just forked the repo I will try to find out

**Comment by mahmoud-the-dev** [comment]
We can't access files out of the root directory, so I guess we have to include the CSS and JS directories within the HTML directory. (I will test this and submit a PR if you have other thoughts share them with me)

according to this image
![image](https://github.com/user-attachments/assets/c9412131-9c53-42ea-ac3c-c302e927b522)

**Comment by anjalit03** [comment]
sure let's try that.... I was also thinking maybe the different directories are causing the issue which is really weird but whatever trying it is worth it
