### ISSUE TITLE
Improving Upcoming Events section UI

### ISSUE THREAD

**Issue by Picodes10** [anjalit03/Dazzle-and-Delight#34]
The "Upcoming Events" heading design needs improvement. Currently, the day number overlaps with the calendar heading, creating a cluttered and difficult-to-read layout. Adequate spacing and style adjustments are required to enhance readability and visual appeal.

Suggested Solutions:

- Use bold styling for the heading to increase prominence.
- Add appropriate spacing between the day numbers and the calendar heading to prevent overlap.
- Adjust the font style and size for improved readability and aesthetic alignment with the overall design.

**Comment by Picodes10** [comment]
@anjalit03 I would like to work on this issue.

**Comment by anjalit03** [comment]
Alright! I've assigned this to you !!
