### ISSUE TITLE
Enhancement: Hover over effect on the checkboxes for visual feedback.

### ISSUE THREAD

**Issue by aldrin312** [anjalit03/Dazzle-and-Delight#37]
Currently its difficult to know if the list of checkbox is active or not. It is also hard to see which one is currently being selected or has been selected.

![image](https://github.com/user-attachments/assets/bf66c730-211e-44ec-8004-577b30a48bd9)

Can I get assigned for this issue?

**Comment by KANDUKURIsaikrishna** [comment]
can you please assign me this issue as part of Hacktoberfest.

**Comment by anjalit03** [comment]
@KANDUKURIsaikrishna sorry this issue is assigned to someone else you can suggest another issue you'd like to work on
