### ISSUE TITLE
Enhancement : Improved Feature events in Home page

### ISSUE THREAD

**Issue by cxde-Sujal** [anjalit03/Dazzle-and-Delight#45]
Featured events card animation and layout needs to be improved as the transitions are not smooth and disturbs other elements .
Even there are spelling errors so need to correct it . @anjalit03 assign it to me for Hacktober.

https://github.com/user-attachments/assets/ed2274a0-cb0b-4835-bbf4-2a6e059a41d2

**assign it to me only 1 PR left to complete for Hacktober ma'am**

**Comment by anjalit03** [comment]
sorry.... someone else is already working on this.... please look for other issues
