### ISSUE TITLE
Validate Email Input in Subscription Section

### ISSUE THREAD

**Issue by Shreyhac** [anjalit03/Dazzle-and-Delight#46]
Currently, the email input field in the subscription section accepts any type of text input. This allows users to enter invalid email formats, which can lead to inaccurate data collection and user experience issues.

Expected Behavior:
When a user enters text in the email input field, the field should only accept valid email formats. If the entered text doesn't match the email format, an error message should appear, indicating that the input is invalid.
<img width="456" alt="Screenshot 2024-10-29 at 22 22 39" src="https://github.com/user-attachments/assets/5851da01-77cf-4fc3-b2ed-ac9322d0a032">

**Comment by Shreyhac** [comment]
please assign me this under hactoberfest

**Comment by anjalit03** [comment]
I've assigned this to you :)

**Comment by Shreyhac** [comment]
thank you so much
