### ISSUE TITLE
UI of home page.

### ISSUE THREAD

**Issue by Rish6392** [anjalit03/Dazzle-and-Delight#48]
![Screenshot 2024-10-29 224032](https://github.com/user-attachments/assets/7b291a9f-9890-4cb5-9e3c-3701a2a82771)
i want to make home page more attractive by adding new css features and home page look more engaging.

**Comment by anjalit03** [comment]
someone else is already working on this, once they are done with it you can check again if there are still changes you'd like to make, please wait till then....
