### ISSUE TITLE
validation for Newsletter

### ISSUE THREAD

**Issue by bdhamithkumara** [anjalit03/Dazzle-and-Delight#56]
issue : currently there is no validation for email input in the Newsletter section

![image](https://github.com/user-attachments/assets/6c0646db-6226-4a12-82f1-29bf48bab0b6)

![123-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/9804e654-880b-42e9-bfc9-46daa67ea7de)

**Comment by anjalit03** [comment]
someone else is already working on this ! please create another issue you'd like to work on :)
