### ISSUE TITLE
Create an about us page 

### ISSUE THREAD

**Issue by anjalit03** [anjalit03/Dazzle-and-Delight#60]
Create an about us page to display more information about the website.

Should include:
- basic information about what the website does
- basic go through of every feature of the website
- info about the developer
- link to the github repository
- message to come and contribute to the website

suggestions on what more can be added are welcome :)

**Comment by malay5** [comment]
Please assign this task to me

**Comment by VoTanTai-dp** [comment]
hey, can you assign this to me?

**Comment by anjalit03** [comment]
@VoTanTai-dp and @hongan2510 this task is already done by someone else please check other issues ....
