### ISSUE TITLE
Create a feedback page

### ISSUE THREAD

**Issue by anjalit03** [anjalit03/Dazzle-and-Delight#61]
Create a feedback page where customers can share their experience, or submit a complaint. Should be aesthetically pleasing and also concise and clear.

**Comment by naikmubashir** [comment]
@anjalit03 I would like to work on issue. Assign it to me...

**Comment by anjalit03** [comment]
I've assigned you :)

**Comment by hongan2510** [comment]
hey, can you assign this to me?

**Comment by giahungb2111886** [comment]
I want to work on issue. Assign it to me pls

**Comment by anjalit03** [comment]
@giahungb2111886 assigned 👍

**Comment by DoHuyThinh** [comment]
i want to do this. Can you assign this to me plss?
