### ISSUE TITLE
Create a code of conduct file for the repository

### ISSUE THREAD

**Issue by anjalit03** [anjalit03/Dazzle-and-Delight#62]
Create a code of conduct file for the repository. Before getting started, make sure to discuss what points you will be adding to the file.

**Comment by naikmubashir** [comment]
@anjalit03  I would like to work on this issue , please  assign it to me.

**Comment by anjalit03** [comment]
Alright!!

**Comment by naikmubashir** [comment]
Should i add the default github code_of_conduct template or a custom one @anjalit03

**Comment by anjalit03** [comment]
default is fine but if you get any ideas for any addition or changes you can suggest them

**Comment by naikmubashir** [comment]
Take a look @anjalit03
