### ISSUE TITLE
Update social media icons 

### ISSUE THREAD

**Issue by cxde-Sujal** [anjalit03/Dazzle-and-Delight#7]
![Screenshot (232)](https://github.com/user-attachments/assets/9f24732e-d348-4af4-8fa9-5d716541761c)
to update the skype logo to the new X logo 
@anjalit03 assign it to me for Hacktober .

**Comment by HarshKumar1121** [comment]
please anjalit03 assign me this .

**Comment by anjalit03** [comment]
@cxde-Sujal are you doing this or if I can assign it to @HarshKumar1121 ?

**Comment by bdhamithkumara** [comment]
I don't think this will take a long time to fix.  can you @anjalit03 please assign it to me?

**Comment by anjalit03** [comment]
@bdhamithkumara alright! I'm assigning you !
