### ISSUE TITLE
Increase Consistency in Navbar

### ISSUE THREAD

**Issue by cxde-Sujal** [anjalit03/Dazzle-and-Delight#8]
To make the color more interactive in Navbar UI . The font sizes could be adjusted assign it to me for Hacktober . @anjalit03 
![Screenshot (233)](https://github.com/user-attachments/assets/f688bae5-2471-4ede-a971-af2f0400e425)

**Comment by anjalit03** [comment]
Sure!! please make sure the changes align with the current website design and style :)
