### ISSUE TITLE
navbar hover effect ui 

### ISSUE THREAD

**Issue by mahenoorsalat** [anjalit03/Dazzle-and-Delight#84]
**Enhancing User Engagement with Effective Navbar Hover Effects**

Assign it to me .. I will look into this 

Thank You :)

Ping @anjalit03

**Comment by anjalit03** [comment]
The navbar has been updated already if you want to you can fix the navbar on the home page it is not properly arranged same for the footer :)

**Comment by mahenoorsalat** [comment]
yeah I can assign me and please label it as hacktoberfest (:

**Comment by mahenoorsalat** [comment]
I am working on it @anjalit03 don't worry about that
